version: "3.8"

services:
  postgres:
    ports:
      - "15432:5432"

  redis:
    ports:
      - "16379:6379"

  meilisearch:
    ports:
      - "17700:7700"

  directus:
    ports:
      - "8055:8055"
